version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./volumes/postgresql/pg1-data:/var/lib/postgresql/data
      - ./src/repository/postgres_repos/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PG_PORT}:5432
  
  test_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER_TEST}
      POSTGRES_PASSWORD: ${PG_PASSWORD_TEST}
      POSTGRES_DB: ${PG_DATABASE_TEST}
    volumes:
      - ./volumes/postgresql/pg-data_test:/var/lib/postgresql/data
      - ./src/repository/postgres_repos/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PG_PORT_TEST}:5432

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"

  test_redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT_TEST}:6379"

volumes:
  src:
