version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./volumes/postgresql/pg1-data:/var/lib/postgresql/data
      - ./src/repository/postgres_repos/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PG_POST}:5432

volumes:
  src:
