info:
  contact: {}
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register endpoint
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get an example endpoint
      tags:
      - example
swagger: "2.0"
